# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dccbd33773eaa9c2a5a370c9591d7490a270d75b5305930a49b5002a5fa1fe45f289a9fdf7a68986af823ae29a11ce3a6070fbe491572fd2b8fc5da7103fcd1e

test:
  secret_key_base: 4ff548300ba153a3a3f59ab742832f8eb59d684b3fd84a4ab43fab0079b3f55b80cfb84ebf29bbe47c1134fe21cdacbe5a32590557c99312f6a817ac7f9e1436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
